### ISSUE TITLE
custom data training

### ISSUE THREAD

**Issue by lerndeep** [d-gurgurov/im2latex#1]
@d-gurgurov 

Thank you for your work.

I would like to ask how can I train your module for custom dataset and process need to follow to prepare custom data?

Thank you

**Comment by d-gurgurov** [comment]
Hi! Thanks for reaching out :)

I think the easiest way for you to fine-tune our model on your custom dataset would be to upload the dataset on HuggingFace and then use the ..finetune_handwritten.py script, where you would have to change the dataset directory from the one we used to yours. It might be the case that you would need to make some changes to the dataset class, depending on the format of your pictures, etc. The script will fine-tune our base model with a LoRa adapter. Hope it'll work for you!
